---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpuexecutioncap: 70
  gui: true

provisione:
  name: chef_zero

platforms:
  - name: box-cutter/ubuntu1404-desktop
  - name: box-cutter/ubuntu1604-desktop

suites:
  - name: default
    run_list:
      - recipe[xmonad::default]
    attributes:
