name             'xmonad'
maintainer       'Matt Chun-Lum'
maintainer_email 'mchunlum@gmail.com'
license          'all_rights'
description      'Installs/Configures xmonad'
long_description 'Installs/Configures xmonad'
version          '0.2.0'

depends 'apt'
depends 'cabal'
